create table customer (id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), kakao_id varchar(255) not null, name varchar(255) not null, partner_custom_id varchar(50) not null, phone_number varchar(20) not null, partner_company_id bigint not null, primary key (id)) engine=InnoDB;
create table live_feedback (live_feedback_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), feedback_media_url varchar(1024), feedback_message varchar(255) not null, is_handled bit not null, is_reported bit not null, is_solved bit not null, response_message varchar(255), reservation_id bigint, primary key (live_feedback_id)) engine=InnoDB;
create table live_satisfaction (live_satisfaction_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), dissatisfied_review_property varchar(255) not null, rating integer not null, satisfied_review_property varchar(255) not null, reservation_id bigint, primary key (live_satisfaction_id)) engine=InnoDB;
create table partner_company (partner_company_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), is_withdrawn bit not null, name varchar(255) not null, domain varchar(255) not null, primary key (partner_company_id)) engine=InnoDB;
create table partner_manager (partner_manager_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), email varchar(255) not null, name varchar(20) not null, password varchar(255) not null, role varchar(255) not null, partner_company_id bigint not null, primary key (partner_manager_id)) engine=InnoDB;
create table partner_seller (partner_seller_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), kakao_id varchar(255) not null, name varchar(20) not null, phone_number varchar(20) not null, partner_company_id bigint not null, primary key (partner_seller_id)) engine=InnoDB;
create table reservation (reservation_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), end_date_time datetime(6) not null, partner_custom_id varchar(50) not null, start_date_time datetime(6) not null, customer_id bigint not null, travel_product_id bigint not null, primary key (reservation_id)) engine=InnoDB;
create table review (review_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), content varchar(255) not null, polarity varchar(255) not null, rating integer not null, title varchar(255) not null, reservation_id bigint, primary key (review_id)) engine=InnoDB;
create table review_image (review_image_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), url varchar(1024) not null, review_id bigint not null, primary key (review_image_id)) engine=InnoDB;
create table review_tag (review_tag_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), end_index integer not null, keyword varchar(255), polarity varchar(255) not null, property varchar(255) not null, start_index integer not null, review_id bigint not null, primary key (review_tag_id)) engine=InnoDB;
create table tour_course (tour_course_id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), end_time datetime(6) not null, name varchar(255) not null, start_time datetime(6) not null, travel_product_id bigint not null, primary key (tour_course_id)) engine=InnoDB;
create table travel_product (dtype varchar(31) not null, id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), name varchar(255) not null, partner_custom_id varchar(50) not null, rating float not null, review_count integer not null, thumbnail_url varchar(1024), category varchar(255) not null, partner_company_id bigint not null, partner_seller_id bigint not null, primary key (id)) engine=InnoDB;
alter table customer add constraint UK_jqufs5nt6ftorw1q8day24dgl unique (kakao_id);
alter table customer add constraint UK_b03a5nhswksk496q0lhl2thxg unique (partner_custom_id);
alter table customer add constraint UK_rosd2guvs3i1agkplv5n8vu82 unique (phone_number);
alter table partner_company add constraint UK_5qwcmihcyqsl3imrr65n1jf0t unique (domain);
alter table partner_seller add constraint UK_gx557ffyuib1234e2uac2uexe unique (kakao_id);
alter table partner_seller add constraint UK_qniynq4iyw0qunvo4wwc7dweu unique (phone_number);
alter table reservation add constraint UK_qsm01m97frgse43kna8spjcvo unique (partner_custom_id);
alter table travel_product add constraint UK_jok17hf1bc9nmy4vraddgkbc8 unique (partner_custom_id);
alter table customer add constraint FKthu0hsarjxs6tre34me6teu20 foreign key (partner_company_id) references partner_company (partner_company_id);
alter table live_feedback add constraint FK778d67w5gckyv1nxw6v6sdny3 foreign key (reservation_id) references reservation (reservation_id);
alter table live_satisfaction add constraint FKi0n132a62oq9nsm2f7oe313ml foreign key (reservation_id) references reservation (reservation_id);
alter table partner_manager add constraint FKlyxgagmx5ngy6jw5h1jvfhul foreign key (partner_company_id) references partner_company (partner_company_id);
alter table partner_seller add constraint FKhyytw7t7mwwdhpw0gr4gdrxk5 foreign key (partner_company_id) references partner_company (partner_company_id);
alter table reservation add constraint FK41v6ueo0hiran65w8y1cta2c2 foreign key (customer_id) references customer (id);
alter table reservation add constraint FK2b47iyl8k0i4w4ag2a63wshw8 foreign key (travel_product_id) references travel_product (id);
alter table review add constraint FK7tyi0jd0eaphyr0gsvfjqww9i foreign key (reservation_id) references reservation (reservation_id);
alter table review_image add constraint FK16wp089tx9nm0obc217gvdd6l foreign key (review_id) references review (review_id);
alter table review_tag add constraint FKea2voymuynf2rmdx7ph30cwoe foreign key (review_id) references review (review_id);
alter table tour_course add constraint FKkgpyslbqhjtwhspfqp45ta48a foreign key (travel_product_id) references travel_product (id);
alter table travel_product add constraint FKj48asg04uy09fss6ddnmh8898 foreign key (partner_company_id) references partner_company (partner_company_id);
alter table travel_product add constraint FKrjl3btw1leqijexob9ryiutra foreign key (partner_seller_id) references partner_seller (partner_seller_id);