openapi: 3.0.1
info:
  title: Review Mate API
  description: Review Mate WAS API
  version: 0.1.0
servers:
- url: https://localhost:8080
tags: []
paths:
  /:
    get:
      summary: 서버 상태를 확인
      description: 서버 상태를 확인
      operationId: greet
      responses:
        "200":
          description: "200"
          content:
            text/plain;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/486549215'
              examples:
                greet:
                  value: hello
components:
  schemas:
    "486549215":
      type: object
